// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/collections-list': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections-list').default>>>>
    }
    '/api/collections/**:path': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/collections/[...path]').default>>>>
    }
    '/api/schema/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/schema/[collection]').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../../../node_modules/.pnpm/@nuxt+nitro-server@3.21.1_better-sqlite3@12.6.2_db0@0.3.4_better-sqlite3@12.6.2__ioredi_4ed600210e3c4c3f1fe11e0b6b005d73/node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}